// apps/admin/src/App.tsx
import { Check, RefreshCw, RotateCcw, Send, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import {
  AdminOrder,
  ReviewQueueItem,
  ReviewQueueStatus,
  createOrderRefund,
  decideProductReview,
  fetchAdminOrders,
  fetchReviewQueue,
  publishProductToPool,
  statusLabels
} from './api';
import './styles.css';

const adminActorUserId = 'admin-user-001';
const statuses: ReviewQueueStatus[] = ['pending_review', 'approved', 'rejected'];

export default function App() {
  const [activeStatus, setActiveStatus] = useState<ReviewQueueStatus>('pending_review');
  const [items, setItems] = useState<ReviewQueueItem[]>([]);
  const [orders, setOrders] = useState<AdminOrder[]>([]);
  const [selectedProductId, setSelectedProductId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const selectedItem = useMemo(
    () => items.find((item) => item.productId === selectedProductId) ?? items[0] ?? null,
    [items, selectedProductId]
  );

  async function loadQueue(status: ReviewQueueStatus) {
    setLoading(true);
    setError(null);
    try {
      const response = await fetchReviewQueue(status);
      setItems(response.items);
      setSelectedProductId(response.items[0]?.productId ?? null);
    } catch (loadError) {
      setItems([]);
      setSelectedProductId(null);
      setError(loadError instanceof Error ? loadError.message : '商品审核队列加载失败');
    } finally {
      setLoading(false);
    }
  }

  async function loadOrders() {
    try {
      const response = await fetchAdminOrders();
      setOrders(response.orders);
    } catch (loadError) {
      setOrders([]);
      setError(loadError instanceof Error ? loadError.message : '订单管理列表加载失败');
    }
  }

  useEffect(() => {
    void loadQueue(activeStatus);
  }, [activeStatus]);

  useEffect(() => {
    void loadOrders();
  }, []);

  async function approve(item: ReviewQueueItem) {
    await runAction(async () => {
      await decideProductReview({ productId: item.productId, action: 'approve', actorUserId: adminActorUserId });
      setMessage(`${item.name} 已通过审核`);
      await loadQueue(activeStatus);
    });
  }

  async function reject(item: ReviewQueueItem) {
    const reason = window.prompt('驳回原因', item.latestReviewLog?.reason ?? '');
    if (!reason?.trim()) {
      return;
    }

    await runAction(async () => {
      await decideProductReview({
        productId: item.productId,
        action: 'reject',
        actorUserId: adminActorUserId,
        reason: reason.trim()
      });
      setMessage(`${item.name} 已驳回`);
      await loadQueue(activeStatus);
    });
  }

  async function publish(item: ReviewQueueItem) {
    await runAction(async () => {
      await publishProductToPool({ productId: item.productId, actorUserId: adminActorUserId });
      setMessage(`${item.name} 已发布到商品池`);
      await loadQueue(activeStatus);
    });
  }

  async function requestRefund(order: AdminOrder) {
    const payment = order.latestPayment;

    if (!payment) {
      return;
    }

    await runAction(async () => {
      const result = await createOrderRefund({
        requestId: `admin-refund-${order.orderNo}-${Date.now()}`,
        paymentNo: payment.paymentNo,
        orderNo: order.orderNo,
        channel: payment.channel,
        refundAmount: order.totalAmount,
        reason: 'after_sale'
      });
      setMessage(`${order.orderNo} 已提交退款申请 ${result.refund.refundNo}`);
      await loadOrders();
    });
  }

  async function runAction(action: () => Promise<void>) {
    setError(null);
    setMessage(null);
    try {
      await action();
    } catch (actionError) {
      setError(actionError instanceof Error ? actionError.message : '操作失败');
    }
  }

  return (
    <main className="shell">
      <header className="topbar">
        <div>
          <p className="eyebrow">商品域基础</p>
          <h1>商品审核工作台</h1>
        </div>
        <button className="icon-button" onClick={() => void loadQueue(activeStatus)} aria-label="刷新队列">
          <RefreshCw size={18} />
        </button>
      </header>

      <nav className="status-tabs" aria-label="审核状态">
        {statuses.map((status) => (
          <button
            key={status}
            type="button"
            className={activeStatus === status ? 'active' : ''}
            onClick={() => setActiveStatus(status)}
          >
            {statusLabels[status]}
          </button>
        ))}
      </nav>

      {message ? <div className="notice success">{message}</div> : null}
      {error ? <div className="notice error">{error}</div> : null}

      <section className="order-panel" aria-label="订单管理">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">订单域</p>
            <h2>订单管理</h2>
          </div>
          <span className="queue-count">{orders.length} 单</span>
        </div>
        <div className="order-list">
          {orders.length === 0 ? <p className="empty-text">暂无订单</p> : null}
          {orders.map((order) => (
            <article className="order-card" key={order.orderNo}>
              <div className="order-card-header">
                <strong>{order.orderNo}</strong>
                <span>{orderStatusLabel(order.status)}</span>
              </div>
              <dl className="order-metrics">
                <div>
                  <dt>买家</dt>
                  <dd>{order.buyerUserId}</dd>
                </div>
                <div>
                  <dt>收货</dt>
                  <dd>{formatReceiver(order)}</dd>
                </div>
                <div>
                  <dt>金额</dt>
                  <dd>合计 {formatMoney(order.totalAmount)}</dd>
                </div>
                <div>
                  <dt>支付</dt>
                  <dd>{formatPayment(order)}</dd>
                </div>
              </dl>
              <div className="order-lines">
                {order.lines.map((line) => (
                  <span key={`${order.orderNo}-${line.displayName}-${line.displaySkuCode ?? 'default'}`}>
                    {line.displayName} x{line.quantity}
                  </span>
                ))}
              </div>
              {canRequestRefund(order) ? (
                <div className="order-actions">
                  <button type="button" onClick={() => void requestRefund(order)}>
                    <RotateCcw size={15} />
                    申请退款
                  </button>
                </div>
              ) : null}
            </article>
          ))}
        </div>
      </section>

      <section className="workbench">
        <div className="table-region">
          <table>
            <thead>
              <tr>
                <th>商品</th>
                <th>商户</th>
                <th>加盟商</th>
                <th>主数据</th>
                <th>产地</th>
                <th>动作</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={6}>加载中</td>
                </tr>
              ) : null}
              {!loading && items.length === 0 ? (
                <tr>
                  <td colSpan={6}>暂无商品</td>
                </tr>
              ) : null}
              {!loading
                ? items.map((item) => (
                    <tr
                      key={item.productId}
                      className={selectedItem?.productId === item.productId ? 'selected' : ''}
                      onClick={() => setSelectedProductId(item.productId)}
                    >
                      <td>
                        <div className="product-cell">
                          <img src={item.primaryImageUrl ?? fallbackImageUrl(item.name)} alt={item.name} />
                          <div>
                            <strong>{item.name}</strong>
                            <span>{item.code}</span>
                            <span>{item.category.name}</span>
                          </div>
                        </div>
                      </td>
                      <td>{item.merchant.name}</td>
                      <td>{item.franchise.name}</td>
                      <td>
                        <div className="metric-line">
                          <span>{item.skuCount} 个 SKU</span>
                          <span>{item.imageCount} 张图</span>
                          <span>{item.qualificationCount} 项资质</span>
                        </div>
                      </td>
                      <td>{formatOrigin(item)}</td>
                      <td>
                        <div className="actions">
                          <button type="button" onClick={(event) => actionClick(event, () => approve(item))}>
                            <Check size={15} />
                            通过审核
                          </button>
                          <button type="button" onClick={(event) => actionClick(event, () => reject(item))}>
                            <X size={15} />
                            驳回审核
                          </button>
                          <button
                            type="button"
                            disabled={item.status !== 'approved'}
                            onClick={(event) => actionClick(event, () => publish(item))}
                          >
                            <Send size={15} />
                            发布商品池
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                : null}
            </tbody>
          </table>
        </div>

        <aside className="detail-panel">
          {selectedItem ? (
            <>
              <img
                className="detail-image"
                src={selectedItem.primaryImageUrl ?? fallbackImageUrl(selectedItem.name)}
                alt={selectedItem.name}
              />
              <h2>{selectedItem.name}</h2>
              <dl>
                <div>
                  <dt>品牌</dt>
                  <dd>{selectedItem.brand?.name ?? '未填写'}</dd>
                </div>
                <div>
                  <dt>参数</dt>
                  <dd>{selectedItem.parameterCount} 项</dd>
                </div>
                <div>
                  <dt>详情图文</dt>
                  <dd>{selectedItem.detailSectionCount} 段</dd>
                </div>
                <div>
                  <dt>最近流转</dt>
                  <dd>{selectedItem.latestReviewLog ? statusActionLabel(selectedItem.latestReviewLog.action) : '无'}</dd>
                </div>
              </dl>
              <div className="review-detail-sections">
                <section className="review-detail-section">
                  <h3>SKU</h3>
                  {selectedItem.primarySku ? (
                    <div className="detail-card">
                      <strong>{selectedItem.primarySku.code}</strong>
                      <span>{selectedItem.primarySku.specText || '未填写规格'}</span>
                      <span>{`销售价 ${formatMoney(selectedItem.primarySku.priceAmount)}`}</span>
                    </div>
                  ) : (
                    <p className="empty-text">暂无 SKU</p>
                  )}
                </section>

                <section className="review-detail-section">
                  <h3>图片</h3>
                  {selectedItem.media.length > 0 ? (
                    <ul className="detail-list">
                      {selectedItem.media.map((media) => (
                        <li key={`${media.type}-${media.url}`}>
                          <strong>{mediaTypeLabel(media.type)}</strong>
                          <span>{media.url}</span>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="empty-text">暂无图片</p>
                  )}
                </section>

                <section className="review-detail-section">
                  <h3>资质</h3>
                  {selectedItem.qualifications.length > 0 ? (
                    <ul className="detail-list">
                      {selectedItem.qualifications.map((qualification) => (
                        <li key={`${qualification.type}-${qualification.title}`}>
                          <strong>{qualification.title}</strong>
                          <span>{qualification.certificateNo ?? '未填写证书编号'}</span>
                          {qualification.fileUrl ? <span>{qualification.fileUrl}</span> : null}
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="empty-text">暂无资质</p>
                  )}
                </section>

                <section className="review-detail-section">
                  <h3>商品参数</h3>
                  {selectedItem.parameters.length > 0 ? (
                    <ul className="detail-list">
                      {selectedItem.parameters.map((parameter) => (
                        <li key={`${parameter.groupName}-${parameter.name}`}>
                          <strong>{`${parameter.name}: ${parameter.value}`}</strong>
                          <span>{parameter.groupName}</span>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="empty-text">暂无参数</p>
                  )}
                </section>

                <section className="review-detail-section">
                  <h3>详情图文</h3>
                  {selectedItem.detailSections.length > 0 ? (
                    <ul className="detail-list">
                      {selectedItem.detailSections.map((section) => (
                        <li key={`${section.type}-${section.sortOrder}`}>
                          <strong>{section.title ?? detailSectionTypeLabel(section.type)}</strong>
                          {section.content ? <span>{section.content}</span> : null}
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="empty-text">暂无详情图文</p>
                  )}
                </section>
              </div>
            </>
          ) : (
            <p>暂无商品</p>
          )}
        </aside>
      </section>
    </main>
  );
}

function actionClick(event: React.MouseEvent<HTMLButtonElement>, action: () => Promise<void>) {
  event.stopPropagation();
  void action();
}

function formatOrigin(item: ReviewQueueItem) {
  return [item.origin.country, item.origin.province, item.origin.city].filter(Boolean).join(' / ');
}

function statusActionLabel(action: string) {
  const labels: Record<string, string> = {
    submit_review: '提交审核',
    approve: '审核通过',
    reject: '审核驳回'
  };

  return labels[action] ?? action;
}

function formatMoney(amount: number) {
  return `¥${(amount / 100).toFixed(2)}`;
}

function formatReceiver(order: AdminOrder) {
  if (order.fulfillmentType === 'pickup') {
    return order.pickupStoreName ?? '到店自提';
  }

  return [order.receiverName, order.receiverPhone, order.receiverAddress].filter(Boolean).join(' / ');
}

function formatPayment(order: AdminOrder) {
  if (!order.latestPayment) {
    return '未生成支付单';
  }

  return `${paymentChannelLabels[order.latestPayment.channel] ?? order.latestPayment.channel} ${
    paymentStatusLabels[order.latestPayment.status] ?? order.latestPayment.status
  }`;
}

function orderStatusLabel(status: string) {
  return orderStatusLabels[status] ?? status;
}

function canRequestRefund(order: AdminOrder) {
  return order.status === 'paid' && order.latestPayment !== null && order.latestPayment.status === 'paid';
}

const orderStatusLabels: Record<string, string> = {
  pending_payment: '待支付',
  paid: '已支付',
  refund_processing: '退款处理中',
  completed: '已完成',
  cancelled: '已取消',
  canceled: '已取消',
  refunded: '已退款'
};

const paymentChannelLabels: Record<string, string> = {
  wechat: '微信支付',
  alipay: '支付宝',
  cash: '现金'
};

const paymentStatusLabels: Record<string, string> = {
  pending: '待支付',
  paid: '已支付',
  failed: '支付失败',
  closed: '已关闭',
  refunded: '已退款'
};

function mediaTypeLabel(type: string) {
  const labels: Record<string, string> = {
    main_image: '主图',
    detail_image: '详情图'
  };

  return labels[type] ?? type;
}

function detailSectionTypeLabel(type: string) {
  const labels: Record<string, string> = {
    text: '文字',
    image: '图片'
  };

  return labels[type] ?? type;
}

function fallbackImageUrl(name: string) {
  const encoded = encodeURIComponent(name.slice(0, 6));
  return `https://placehold.co/320x220/f6f8fb/2f3a4a?text=${encoded}`;
}

// apps/portal/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import {
  createPortalOrder,
  createPortalPayment,
  fetchProductPoolCatalog,
  fetchProductPoolItemDetail,
  fetchPortalOrderDetail,
  fetchPortalOrders,
  type PortalCheckoutOrder,
  type PortalOrderRecord,
  type PortalPayment,
  type ProductPoolCatalog,
  type ProductPoolCatalogItem,
  type ProductPoolItemDetail
} from './api';

const localBuyerUserId = 'local-user-001';
const localDelivery = {
  receiverName: '本地用户',
  receiverPhone: '13800000000',
  receiverAddress: '本地联调地址'
};

const loading = ref(true);
const error = ref<string | null>(null);
const productPools = ref<ProductPoolCatalog[]>([]);
const detailLoading = ref(false);
const detailError = ref<string | null>(null);
const selectedDetail = ref<ProductPoolItemDetail | null>(null);
const checkoutLoading = ref(false);
const checkoutError = ref<string | null>(null);
const createdOrder = ref<PortalCheckoutOrder | null>(null);
const ordersLoading = ref(true);
const ordersError = ref<string | null>(null);
const orders = ref<PortalOrderRecord[]>([]);
const orderDetailLoading = ref(false);
const orderDetailError = ref<string | null>(null);
const selectedOrder = ref<PortalOrderRecord | null>(null);
const paymentLoading = ref(false);
const paymentError = ref<string | null>(null);
const createdPayment = ref<PortalPayment | null>(null);

const totalItems = computed(() => productPools.value.reduce((total, pool) => total + pool.items.length, 0));
const originText = computed(() => {
  const origin = selectedDetail.value?.product.origin;
  if (!origin) {
    return '产地信息待补充';
  }

  return [origin.country, origin.province, origin.city, origin.description].filter(Boolean).join(' / ');
});

onMounted(() => {
  void Promise.all([loadCatalog(), loadLocalOrders()]);
});

async function loadCatalog() {
  loading.value = true;
  error.value = null;

  try {
    const response = await fetchProductPoolCatalog();
    productPools.value = response.productPools;
  } catch (loadError) {
    productPools.value = [];
    error.value = loadError instanceof Error ? loadError.message : '商品池加载失败';
  } finally {
    loading.value = false;
  }
}

async function loadLocalOrders() {
  ordersLoading.value = true;
  ordersError.value = null;

  try {
    const response = await fetchPortalOrders(localBuyerUserId);
    orders.value = response.orders ?? [];
  } catch (loadError) {
    orders.value = [];
    ordersError.value = loadError instanceof Error ? loadError.message : '订单列表加载失败';
  } finally {
    ordersLoading.value = false;
  }
}

async function openProductDetail(item: ProductPoolCatalogItem) {
  detailLoading.value = true;
  detailError.value = null;
  selectedDetail.value = null;
  checkoutError.value = null;
  createdOrder.value = null;

  try {
    selectedDetail.value = await fetchProductPoolItemDetail(item.id);
  } catch (loadError) {
    detailError.value = loadError instanceof Error ? loadError.message : '商品详情加载失败';
  } finally {
    detailLoading.value = false;
  }
}

async function openOrderDetail(order: PortalOrderRecord) {
  orderDetailLoading.value = true;
  orderDetailError.value = null;
  selectedOrder.value = null;
  paymentError.value = null;
  createdPayment.value = null;

  try {
    const response = await fetchPortalOrderDetail({
      orderNo: order.orderNo,
      buyerUserId: localBuyerUserId
    });
    selectedOrder.value = response.order;
  } catch (loadError) {
    orderDetailError.value = loadError instanceof Error ? loadError.message : '订单详情加载失败';
  } finally {
    orderDetailLoading.value = false;
  }
}

function closeOrderDetail() {
  orderDetailError.value = null;
  paymentError.value = null;
  selectedOrder.value = null;
  createdPayment.value = null;
}

function closeProductDetail() {
  detailError.value = null;
  checkoutError.value = null;
  selectedDetail.value = null;
  createdOrder.value = null;
}

function formatMoney(amount: number) {
  return `¥${(amount / 100).toFixed(2)}`;
}

function statusText(status: string) {
  const labels: Record<string, string> = {
    pending_payment: '待支付',
    paid: '已支付',
    completed: '已完成',
    cancelled: '已取消',
    refund_processing: '退款中',
    refunded: '已退款'
  };

  return labels[status] ?? status;
}

function paymentStatusText(status: string) {
  const labels: Record<string, string> = {
    pending: '待支付',
    paid: '已支付',
    failed: '支付失败'
  };

  return labels[status] ?? status;
}

function paymentChannelText(channel: string) {
  const labels: Record<string, string> = {
    wechat: '微信支付',
    alipay: '支付宝',
    cash: '现金'
  };

  return labels[channel] ?? channel;
}

function paymentSummaryText(payment: PortalPayment) {
  return `${paymentChannelText(payment.channel)} · ${paymentStatusText(payment.status)}`;
}

function createCheckoutRequestId(itemId: string) {
  const safeItemId = itemId.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return `portal-checkout-${safeItemId}-${Date.now()}`;
}

function createPaymentRequestId(orderNo: string) {
  const safeOrderNo = orderNo.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return `portal-payment-${safeOrderNo}-${Date.now()}`;
}

async function submitLocalOrder() {
  if (!selectedDetail.value) {
    checkoutError.value = '请先选择商品';
    return;
  }

  checkoutLoading.value = true;
  checkoutError.value = null;
  createdOrder.value = null;

  try {
    const result = await createPortalOrder({
      requestId: createCheckoutRequestId(selectedDetail.value.id),
      buyerUserId: localBuyerUserId,
      productPoolItemId: selectedDetail.value.id,
      quantity: 1,
      welfareCardPaymentAmount: 0,
      fulfillment: {
        type: 'delivery',
        ...localDelivery
      }
    });
    createdOrder.value = result.order;
    await loadLocalOrders();
  } catch (submitError) {
    checkoutError.value = submitError instanceof Error ? submitError.message : '订单创建失败';
  } finally {
    checkoutLoading.value = false;
  }
}

async function submitLocalPayment() {
  if (!selectedOrder.value) {
    paymentError.value = '请先选择订单';
    return;
  }

  paymentLoading.value = true;
  paymentError.value = null;
  createdPayment.value = null;

  try {
    const result = await createPortalPayment({
      requestId: createPaymentRequestId(selectedOrder.value.orderNo),
      orderNo: selectedOrder.value.orderNo,
      channel: 'wechat',
      totalAmount: selectedOrder.value.totalAmount,
      welfareCardPayableAmount: selectedOrder.value.welfareCardPayableAmount,
      cashPayableAmount: selectedOrder.value.cashPayableAmount
    });
    createdPayment.value = result.payment;
    selectedOrder.value = {
      ...selectedOrder.value,
      latestPayment: result.payment
    };
    await loadLocalOrders();
  } catch (submitError) {
    paymentError.value = submitError instanceof Error ? submitError.message : '支付单创建失败';
  } finally {
    paymentLoading.value = false;
  }
}
</script>

<template>
  <main class="portal-shell">
    <header class="portal-topbar">
      <div>
        <p class="eyebrow">商品池</p>
        <h1>企业福利商品目录</h1>
      </div>
      <button type="button" class="refresh-button" @click="loadCatalog">刷新</button>
    </header>

    <section class="summary-band">
      <div>
        <span>可选商品</span>
        <strong>{{ totalItems }}</strong>
      </div>
      <div>
        <span>启用商品池</span>
        <strong>{{ productPools.length }}</strong>
      </div>
    </section>

    <section class="orders-section" aria-live="polite">
      <div class="section-heading">
        <div>
          <p class="eyebrow">本地用户</p>
          <h2>我的订单</h2>
        </div>
        <button type="button" class="secondary-button" :disabled="ordersLoading" @click="loadLocalOrders">
          {{ ordersLoading ? '刷新中' : '刷新订单' }}
        </button>
      </div>

      <p v-if="ordersLoading" class="state-text compact">订单加载中</p>
      <p v-else-if="ordersError" class="state-text error">{{ ordersError }}</p>
      <p v-else-if="orders.length === 0" class="state-text compact">暂无订单</p>
      <div v-else class="order-list">
        <button
          v-for="order in orders"
          :key="order.orderNo"
          type="button"
          class="order-row"
          :aria-label="`查看订单 ${order.orderNo} 详情`"
          @click="openOrderDetail(order)"
        >
          <span>{{ order.orderNo }}</span>
          <strong>{{ formatMoney(order.totalAmount) }}</strong>
          <em>{{ statusText(order.status) }}</em>
          <small v-if="order.latestPayment" class="order-payment-summary">
            最近支付 {{ order.latestPayment.paymentNo }} · {{ paymentSummaryText(order.latestPayment) }}
          </small>
        </button>
      </div>
    </section>

    <section v-if="orderDetailLoading || orderDetailError || selectedOrder" class="order-detail-section" aria-live="polite">
      <div class="section-heading">
        <div>
          <p class="eyebrow">订单详情</p>
          <h2>{{ selectedOrder?.orderNo ?? '正在加载订单详情' }}</h2>
        </div>
        <button type="button" class="secondary-button" @click="closeOrderDetail">关闭订单</button>
      </div>

      <p v-if="orderDetailLoading" class="state-text compact">订单详情加载中</p>
      <p v-else-if="orderDetailError" class="state-text error">{{ orderDetailError }}</p>
      <div v-else-if="selectedOrder" class="order-detail-body">
        <div class="order-facts">
          <div>
            <span>订单状态</span>
            <strong>{{ statusText(selectedOrder.status) }}</strong>
          </div>
          <div>
            <span>订单金额</span>
            <strong>{{ formatMoney(selectedOrder.totalAmount) }}</strong>
          </div>
          <div>
            <span>收货人</span>
            <strong>{{ selectedOrder.receiverName ?? '待补充' }}</strong>
          </div>
          <div>
            <span>配送地址</span>
            <strong>{{ selectedOrder.receiverAddress ?? selectedOrder.pickupStoreName ?? '待补充' }}</strong>
          </div>
        </div>
        <div class="order-line-list">
          <article v-for="line in selectedOrder.lines" :key="line.id" class="order-line">
            <img :src="line.displayImageUrl" :alt="line.displayName" />
            <div>
              <h3>{{ line.displayName }}</h3>
              <p>{{ line.displaySkuCode ?? '默认规格' }} · x{{ line.quantity }}</p>
            </div>
            <strong>{{ formatMoney(line.lineTotalAmount) }}</strong>
          </article>
        </div>
        <section v-if="selectedOrder.latestPayment" class="payment-block persisted-payment">
          <div>
            <h3>最近支付</h3>
            <p>{{ paymentSummaryText(selectedOrder.latestPayment) }}</p>
          </div>
          <div class="checkout-result">
            <span>支付单</span>
            <strong>{{ selectedOrder.latestPayment.paymentNo }}</strong>
            <p>{{ formatMoney(selectedOrder.latestPayment.cashPayableAmount) }}</p>
          </div>
        </section>
        <section v-if="selectedOrder.status === 'pending_payment'" class="payment-block">
          <div>
            <h3>本地支付</h3>
            <p>微信支付 · 应付 {{ formatMoney(selectedOrder.cashPayableAmount) }}</p>
          </div>
          <button
            type="button"
            class="checkout-button"
            :aria-label="`为订单 ${selectedOrder.orderNo} 发起支付`"
            :disabled="paymentLoading"
            @click="submitLocalPayment"
          >
            {{ paymentLoading ? '创建中' : '发起支付' }}
          </button>
          <p v-if="paymentError" class="checkout-message error">{{ paymentError }}</p>
          <div v-if="createdPayment" class="checkout-result">
            <span>支付单创建成功</span>
            <strong>{{ createdPayment.paymentNo }}</strong>
            <p>{{ paymentChannelText(createdPayment.channel) }} · {{ paymentStatusText(createdPayment.status) }}</p>
          </div>
        </section>
      </div>
    </section>

    <p v-if="loading" class="state-text">加载中</p>
    <p v-else-if="error" class="state-text error">{{ error }}</p>
    <p v-else-if="totalItems === 0" class="state-text">暂无可展示商品</p>

    <div v-else class="pool-list">
      <section v-for="pool in productPools" :key="pool.id" class="pool-section">
        <div class="pool-heading">
          <div>
            <h2>{{ pool.name }}</h2>
            <p>{{ pool.code }}</p>
          </div>
          <span>{{ pool.items.length }} 个商品</span>
        </div>

        <div v-if="pool.items.length === 0" class="state-text compact">暂无可展示商品</div>
        <div v-else class="product-grid">
          <button
            v-for="item in pool.items"
            :key="item.id"
            type="button"
            class="product-card"
            :aria-label="`查看 ${item.displayName} 详情`"
            @click="openProductDetail(item)"
          >
            <img :src="item.displayImageUrl" :alt="item.displayName" />
            <div class="product-body">
              <h3>{{ item.displayName }}</h3>
              <p>{{ item.displaySkuCode ?? '默认规格' }}</p>
              <strong>{{ formatMoney(item.displayPriceAmount) }}</strong>
            </div>
          </button>
        </div>
      </section>
    </div>

    <section v-if="detailLoading || detailError || selectedDetail" class="detail-section" aria-live="polite">
      <div class="detail-heading">
        <div>
          <p class="eyebrow">商品详情</p>
          <h2>{{ selectedDetail?.displayName ?? '正在加载商品详情' }}</h2>
        </div>
        <button type="button" class="close-button" @click="closeProductDetail">关闭详情</button>
      </div>

      <p v-if="detailLoading" class="state-text compact">详情加载中</p>
      <p v-else-if="detailError" class="state-text error">{{ detailError }}</p>
      <div v-else-if="selectedDetail" class="detail-layout">
        <img :src="selectedDetail.displayImageUrl" :alt="selectedDetail.displayName" class="detail-image" />
        <div class="detail-content">
          <div class="detail-price-row">
            <strong>{{ formatMoney(selectedDetail.displayPriceAmount) }}</strong>
            <span>{{ selectedDetail.displaySkuCode ?? selectedDetail.sku?.code ?? '默认规格' }}</span>
          </div>
          <dl class="detail-facts">
            <div>
              <dt>商品编码</dt>
              <dd>{{ selectedDetail.product.code }}</dd>
            </div>
            <div>
              <dt>品牌</dt>
              <dd>{{ selectedDetail.product.brand?.name ?? '未设置品牌' }}</dd>
            </div>
            <div>
              <dt>分类</dt>
              <dd>{{ selectedDetail.product.category?.name ?? '未设置分类' }}</dd>
            </div>
            <div>
              <dt>产地</dt>
              <dd>{{ originText }}</dd>
            </div>
            <div v-if="selectedDetail.sku?.specText">
              <dt>规格</dt>
              <dd>{{ selectedDetail.sku.specText }}</dd>
            </div>
          </dl>

          <section v-if="selectedDetail.product.parameters.length > 0" class="detail-block">
            <h3>商品参数</h3>
            <ul>
              <li v-for="parameter in selectedDetail.product.parameters" :key="`${parameter.groupName}-${parameter.name}`">
                <span>{{ parameter.name }}</span>
                <strong>{{ parameter.value }}</strong>
              </li>
            </ul>
          </section>

          <section v-if="selectedDetail.product.qualifications.length > 0" class="detail-block">
            <h3>资质信息</h3>
            <ul>
              <li v-for="qualification in selectedDetail.product.qualifications" :key="qualification.title">
                <span>{{ qualification.title }}</span>
                <strong>{{ qualification.certificateNo ?? '证书待上传' }}</strong>
              </li>
            </ul>
          </section>

          <section v-if="selectedDetail.product.detailSections.length > 0" class="detail-block">
            <h3>图文说明</h3>
            <article v-for="section in selectedDetail.product.detailSections" :key="`${section.title}-${section.sortOrder}`">
              <h4>{{ section.title ?? '商品说明' }}</h4>
              <p>{{ section.content }}</p>
            </article>
          </section>

          <section class="checkout-block">
            <div>
              <h3>本地下单</h3>
              <p>数量 1，配送至 {{ localDelivery.receiverAddress }}</p>
            </div>
            <button
              type="button"
              class="checkout-button"
              :aria-label="`为 ${selectedDetail.displayName} 创建订单`"
              :disabled="checkoutLoading"
              @click="submitLocalOrder"
            >
              {{ checkoutLoading ? '创建中' : '立即下单' }}
            </button>
            <p v-if="checkoutError" class="checkout-message error">{{ checkoutError }}</p>
            <div v-if="createdOrder" class="checkout-result">
              <span>订单创建成功</span>
              <strong>{{ createdOrder.orderNo }}</strong>
              <p>{{ statusText(createdOrder.status) }} · {{ formatMoney(createdOrder.totalAmount) }}</p>
            </div>
          </section>
        </div>
      </div>
    </section>
  </main>
</template>
